name: CI Cache Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: prime-cache-820edea
        id: prime-cache-820edea
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-820edea
      - name: echo cache status
        run: echo Cache hit status: `${{ steps.prime-cache-820edea.outputs.cache-hit }}`
